from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery
from plugins.helper.db import db
import time
import random
import asyncio
from config import *
from plugins.Post.admin_panel import admin_filter

@Client.on_message(filters.command("genlink") & filters.private & admin_filter)
async def generate_invite_links(client, message: Message):
    try:
        await message.react(emoji=random.choice(REACTIONS), big=True)
    except:
        pass
    
    if not await db.is_admin(message.from_user.id):
        await message.reply("❌ You are not authorized to use this command!")
        return
    
    channels = await db.get_all_channels()
    
    if not channels:
        await message.reply("No channels connected yet. 🙁")
        return
    
    processing_msg = await message.reply("⏳ Generating fresh invite links for all channels...")
    
    links_list = []
    errors = []
    
    for channel in channels:
        try:
            # Create new invite link (requires admin rights)
            invite_link = await client.create_chat_invite_link(
                chat_id=channel['_id'],
                name=f"Generated by bot on {time.strftime('%Y-%m-%d')}",
                creates_join_request=False
            )
            links_list.append(f"🔗 [{channel['name']}]({invite_link.invite_link})")
        except Exception as e:
            errors.append(f"❌ {channel['name']} - {str(e)}")
            continue
    
    result_message = "**🌐 Fresh Invite Links:**\n\n" + "\n".join(links_list)
    
    if errors:
        result_message += "\n\n**⚠️ Errors:**\n" + "\n".join(errors)
    
    # Split long messages
    if len(result_message) > 4096:
        parts = [result_message[i:i+4096] for i in range(0, len(result_message), 4096)]
        for part in parts:
            await message.reply(part, disable_web_page_preview=True)
            await asyncio.sleep(1)
    else:
        await message.reply(result_message, disable_web_page_preview=True)
    
    await processing_msg.delete()

# Command to add the current channel to the database
@Client.on_message(filters.command("add") & filters.channel)
async def add_current_channel(client, message: Message):
    channel_id = message.chat.id
    channel_name = message.chat.title

    try:
        added = await db.add_channel(channel_id, channel_name)
        if added:
            await message.reply(f"**Channel '{channel_name}' added! ✅**")
        else:
            await message.reply(f"ℹ️ Channel '{channel_name}' already exists.")
    except Exception as e:
        print(f"Error adding channel: {e}")
        await message.reply("❌ Failed to add channel. Contact developer.")

# Command to remove the current channel from the database
@Client.on_message(filters.command("rem") & filters.channel)
async def remove_current_channel(client, message: Message):
    channel_id = message.chat.id
    channel_name = message.chat.title

    try:
        if await db.is_channel_exist(channel_id):
            await db.delete_channel(channel_id)
            await message.reply(f"**Channel '{channel_name}' removed from my database!**")
        else:
            await message.reply(f"ℹ️ Channel '{channel_name}' not found.")
    except Exception as e:
        print(f"Error removing channel: {e}")
        await message.reply("❌ Failed to remove channel. Try again.")

# Command to list all connected channels
@Client.on_message(filters.command("channels") & filters.private & admin_filter)
async def list_channels(client, message: Message):
    try:
        await message.react(emoji=random.choice(REACTIONS), big=True)
    except:
        pass
    if not await db.is_admin(message.from_user.id):
        await message.reply("**❌ You are not authorized to use this command!**")
        return
    channels = await db.get_all_channels()

    if not channels:
        await message.reply("**No channels connected yet.🙁**")
        return

    total_channels = len(channels)
    channel_list = [f"• **{channel['name']}** :- `{channel['_id']}`" for channel in channels]

    header = f"> **Total Channels :- ({total_channels})**\n\n"
    messages = []
    current_message = header

    for line in channel_list:
        if len(current_message) + len(line) + 1 > 4096:
            messages.append(current_message)
            current_message = ""
        current_message += line + "\n"

    if current_message:
        messages.append(current_message)

    for part in messages:
        await message.reply(part)

