import os
import re
from pyrogram import Client, filters
from pyrogram.types import Message
from config import *

# Complete chapter data extracted from the PDF
CHAPTER_DATA = {
    'Physics': [
        'Basic Maths & Calculus', 'Trigonometry', 'Algebra', 'Binomial', 'AP', 'GP', 'Graphs', 
        'Logarithms', 'Coordinate Geometry', 'Differentiation', 
        'Units and Measurements', 'Physical Quantities and Units', 'Dimensions and Dimensions formula', 
        'Dimensional Analysis', 'Significant Figures', 'Errors in Measurement', 'Measuring Instruments', 
        'Vectors', 'Introduction of vector and scalar', 'Types of vectors', 'Vector addition', 
        'vector subtraction', 'Resolution of vectors', 'Multiplication of a vector by scalar', 
        'Scalar product', 'Vector product', 'Vector Projection', 'Motion in a straight line', 
        'Introduction of mechanics', 'frame of reference', 'distance and displacement', 
        'Average speed and average velocity', 'Instantaneous velocity and its speed', 'Acceleration', 
        'Uniform motion', 'Uniform acceleration', 'Motion under gravity', 'Free fall motion', 
        'Graph of 1D motion', 'variable acceleration', 'Motion in a plane', 'Projectile motion', 
        'Relative motion', 'Circular motion', 'Laws of motion', 'Force', 'Newton\'s first law of motion', 
        'Linear momentum', 'Newton\'s second law of motion', 'Newton\'s third law of motion', 
        'Free body diagram', 'Working with newton\'s first law', 'Working with newton\'s second law', 
        'Calculation of acceleration', 'Spring force', 'Frame of reference', 'Rocket propulsion', 
        'Friction', 'Types of friction', 'Graph between applied force and force of friction', 
        'Angle of friction and angle of repose', 'Acceleration of body on a rough surface', 
        'Dynamics of circular motion', 'Work, energy and power', 'Work', 'Energy', 'work energy theorem', 
        'conservative and non-conservative force', 'potential energy', 'equilibrium', 
        'Centre of mass and System of Particles', 'centre of mass', 'centre of gravity', 'collision', 
        'head-on collision', 'Rotational Motion', 'Introduction', 'rigid body', 'moment of inertia', 
        'theorems of moment of inertia', 'radius of gyration', 'torque', 'newtons laws for rotation', 
        'angular momentum', 'rotational kinetic energy', 'conservation of total mechanical energy', 
        'rolling motion', 'rolling motion on inclined plane', 'comparison between translational and rotational motion', 
        'Gravitation', 'law of gravitation', 'acceleration due to gravity', 'gravitational potential energy', 
        'gravitational potential', 'relation between field and potential', 'escape velocity', 
        'satellite motion', 'kepler\'s law of planetary motion', 'Mechanical Properties of Solids', 
        'elasticity', 'stress', 'strain', 'hooke\'s law', 'modulus of elasticity', 'young\'s modulus', 
        'Mechanical Properties of Fluids', 'introduction of hydrostatics', 'pressure', 'pascal\'s law', 
        'buoyancy', 'buoyant force', 'hydrodynamics', 'equation of continuity', 'bernoulli\' theorem', 
        'viscosity', 'surface tension', 'Thermal Properties of matter', 'thermal expansion', 
        'application of thermal expansion', 'specific heat capacity', 'latent heat', 'calorimetry', 
        'heat transfer', 'conduction', 'convection', 'radiation', 'Kinetic Theory', 'ideal gases', 
        'real gas equation', 'kinetic theory of gases', 'different speed of gas molecules', 
        'Thermodynamics', 'introduction', 'thermal equilibrium and zeroth law', 'first law of thermodynamics', 
        'different type of processes', 'second law of thermodynamics', 'heat engine', 'carnot cycle', 
        'carnot engine', 'heat pump', 'refrigerator', 'Oscillations', 'periodic motion and oscillatory motion', 
        'some basic terms related with oscillatory motion', 'simple harmonic motion(SHM)', 'equations of SHM', 
        'Energy in SHM', 'calculation of time period of spring block system', 'Waves', 'waves', 
        'equation of waves', 'characteristic of waves', 'progressive wave on string', 
        'velocity of transverse wave on string', 'intensity of waves', 'sound waves', 
        'speed of sound wave', 'characteristic of sound wave', 'principle of superposition of wave', 
        'reflection and refraction of waves', 'stationary waves', 'comparison of progressive and stationary waves', 
        'echo', 'Electric Charges and Fields', 'Introduction', 'Charge', 'Coulomb\'s Law', 
        'Electric Field', 'Conductors and Insulators', 'Electric Field of a Continuous Charge Distribution', 
        'Motion of a Charged Particle in Uniform Electric Field', 'Electric Field Lines', 'Electric Flux', 
        'Gauss Law', 'Application of gauss\'s law', 'Electric Dipole', 'Dipole in a Uniform External Field', 
        'Short Dipole in Non-Uniform Electric Field', 'Electrostatic Potential and Capacitance', 
        'Relation between Electric field (E) & Electric potential (V)', 'Equipotential Surface', 
        'Electrostatic potential energy', 'Electric potential due to dipole', 'Electrostatics of Conductor', 
        'Conductor & its capacitance', 'Capacitor & its capacitance', 'Charging of a capacitor', 
        'Combination of capacitors', 'Current Electricity', 'Electric Current', 'Current in Conductors', 
        'Kirchhoff\'s Laws and Combination of Resistances', 'Wheatstone Bridge and Symmetric Circuits', 
        'Electrical Measuring Instruments', 'Moving Charges and Magnetism', 'Introduction', 
        'Biot-Savart\'s Law', 'Magnetic-field due to a current carrying Ring and Problems on combination of Ring and Rod', 
        'Ampere\'s Law and Its applications', 'Force on a moving charge in a Magnetic Field', 
        'Helical Path,Lorentz Force and Velocity Selector', 'Magnetism and Matter', 'Bar Magnet and its Properties', 
        'Circular coil as magnetic dipole', 'Tangent Galvanometer', 'Oscillation Magnetometer', 
        'Magnetisation and Magnetic Intensity', 'Classification of Magnetic Materials', 
        'Electromagnetic Induction', 'Magnetic Flux and Lenz\'s Law', 'Faraday\'s Law', 
        'Calculation of Induced EMF', 'Induced Electric Field', 'Self Inductance', 'Mutual Inductance', 
        'Inductor in Electrical Circuits', 'Alternating Current', 'Introduction to Alternating Current', 
        'Average and RMS Values', 'Types of AC Circuits, Power & Power Factor', 'Electromagnetic Waves', 
        'Characteristics of Electromagnetic Waves', 'Ray Optics and Optical Instruments', 
        'Introduction of optics', 'Reflection of light', 'Reflection from a plane mirror', 
        'Reflection from spherical mirror', 'Refraction of light', 'refraction from a plane surface', 
        'Total internal refraction', 'refraction from curved surface', 'combination of lens and power', 
        'Newton\'s Formula', 'Combination of lens and mirror', 'Displacement method to find the focal length', 
        'refraction from prism', 'Wave Optics', 'wave nature of light', 'nature of light', 
        'interference of light', 'Dual Nature of Radiation and Matter', 'quantum theory of light', 
        'photoelectric effect', 'Atoms', 'atomic model', 'rutherford model', 'Nuclei', 'nuclei', 
        'mass energy', 'Semiconductor Electronics: Materials, Devices and Simple Circuits', 
        'Introduction to Semiconductors', 'Intrinsic and Extrinsic Semiconductor', 'PN Junction Diode', 
        'Application of P-N Junction Diode'
    ],
    'Inorganic Chemistry': [
        'Classification of Elements and Periodicity in Properties', 'Introduction,Need for Classification of Elements',
        'Structural part of modern periodic table , electronic configurations', 'Screening Effect and effective nuclear charge',
        'Atomic Radius', 'Ionisation Enthalpy', 'Electron affinity', 'Electronegativity', 'Nature of Oxides',
        'Historical Development of Classification of Elements', 'Chemical Bonding and Molecular Structure',
        'Kössel - Lewis Approach to Chemical Bonding ,Octet Rule', 'Formal Charge, Covalency, coordinate bond',
        'VSEPR Theory', 'Valence Bond Theory (VBT), hybridisation applications of hybridisation', 'Overlapping',
        'Bond identity, bond strength orders', 'Dipole moment', 'Ionic bond , gen properties of ionic compounds',
        'Lattice energy ,fajans rule', 'Applications of fajans rule', 'MOT', 'Hydrogen Bonding', 'Dipole based forces',
        'Co-ordination Compound', 'Definitions of Some Important Terms Pertaining to Coordination Compounds',
        'Classification of Ligands', 'Nomenclature of Coordination Compounds', 'Werner Theory & EAN Rule', 'VBT', 'CFT',
        'Isomerism in Coordination Compounds', 'Bonding in Metal Carbonyls', 'Applications of complexes',
        'The d and f-Block Elements', 'General Properties of the Transition Elements (d-Block)',
        'Preparation and properties of KMnO4 &K2Cr2O7', 'The Lanthanoids and The Actinoids',
        'The p-Block Elements', 'Introduction', 'Group-13', 'Group-14', 'Group-15', 'Group-16', 'Group-17', 'Group-18',
        'Salt Analysis', 'Introduction of salt and solubility', 'Test of Anions', 'Test of cation', 'Confirmatory Test'
    ],
    'Organic Chemistry': [
        'Organic Chemistry: Some Basic principles and Techniques', 'IUPAC Naming',
        'Tetravalency of carbon: Shapes of Simple molecules - hybridization (s and p)',
        'Classification of organic compounds based on functional groups', 'Degree of Carbon, Hydrogen, Alcohol, Amine',
        'Degree of Unsaturation, Functional Group', 'IUPAC of Alkane', 'IUPAC of Alkene, Cycloalkene',
        'IUPAC of Functional Group', 'Polyfunctional Group', 'IUPAC of Aromatic Compound', 'Common Naming',
        'Isomerism', 'Type of Isomerism Classification and Structural Isomerism', 'Geometrical isomerism',
        'Cis trans Z/E CIP rule', 'Special cases of G.I', 'Calculation of G.I',
        'Conformations: Sawhorse and Newman projections (of ethane, butane cyclohexane )',
        'Optical isomerism: Basics Polarimeter experiment and Chiral Centre,Stereo Centre',
        'Optical isomerism, Plane of symmetry and Center of symmetry', 'Optical isomerism, Fischer Projection & R,S configuration',
        'Optical isomerism, Exihibition of Optical isomerism', 'Enantiomers, Diastereomers, Racemic Mixture Resolution Meso Compound',
        'Pseudo Chiral Centre', 'D,L Configuration, Erythro, Threo, Epimer, Anomers', 'Calculating number of optical and stereoisomers',
        'GOC', 'Covalent bond fission - Homolytic and heterolytic & Inductive Effect', 'Hyperconjugation',
        'Application of Hyperconjugation', 'Resonance', 'Stability of resonating Structures', 'Aromaticity, Annulene',
        'Mesomeric Effect', 'Stability of Intermediates, Bond Length and Bond Strength', 'Acidic Strength', 'Basic Strength',
        'Tautomerism ( Enol Content) electrophiles, and nucleophiles', 'Type of reactions Substitution, addition, elimination, and rearrangement',
        'Hydrocarbon', 'Basic Organic Chemistry', 'Rearrangement of Carbocation, Types of Reaction',
        'Method of Preparation of Alkane', 'Chemical Properties of Alkane : Mechanism of halogenation of alkanes',
        'Physical Properties of Alkane', 'Method of Preparation of Alkene', 'Mechanism of electrophilic addition',
        'addition of hydrogen, halogens', 'Water, hydrogen halides (Markownikoffs and peroxide effect)',
        'Ozonolysis and polymerization', 'Method of Preparation of Alkyne', 'Chemical Properties of Alkyne',
        'Acidic character: Addition of hydrogen, halogens, water, and hydrogen halides: Polymerization',
        'MOP of benzene - Properties of Benzene', 'Mechanism of electrophilic substitution: halogenation, nitration',
        'Friedel - Craft\'s alkylation and acylation', 'directive influence of the functional group in mono substituted benzene',
        'Haloalkanes and Haloarenes', 'Methods of preparation of haloalkanes', 'Chemical Properties of Haloalkane',
        'Nature of C-X bond; Mechanisms of substitution reactions', 'Elimination Reactions', 'Reaction with metals',
        'Uses; Environmental effects of chloroform, iodoform freons, and DDT', 'Methods of preparation of haloarenes',
        'Chemical Properties of Haloarenes: Mechanism of Aromatic nucleophilic substitution reaction & Benzyne mechanism',
        'Method of Preparation of Grignard reagent', 'Chemical Properties of Grignard Reagent',
        'Alcohols, Ethers and Phenols', 'Introduction to alcohols: identification of primary secondary & tertiary alcohols',
        'Preparation of alcohols: mechanism of dehydration', 'Chemical properties of alcohols',
        'Preparation of Phenol: Acidic nature, electrophilic substitution reactions: halogenation. nitration and sulphonation',
        'Reimer - Tiemann reaction & Kolbe\'s Reaction', 'Preparation, Structure of Ethers, Chemical properties of ethers',
        'Epoxides (Oxiranes)', 'Physical Properties of Alcohol, Phenol and Ether',
        'Aldehydes, Ketones and Carboxylic Acids', 'Method of Preparation of Both Aldehyde and Ketone',
        'Method of Preparation of Aldehyde only and Ketone only', 'Nature of carbonyl group;Nucleophilic addition to >C=O group',
        'relative reactivities of aldehydes and ketones', 'Cyanohydrin formation , NaHSO3 addition',
        'Reaction of carbonyl compounds with Alcohols and NH2Z', 'Aldol condensation and cannizzaro reaction',
        'Haloform reaction & Chemical tests to distinguish between aldehydes and Ketones',
        'Method of Preparation of Carboxylic Acid', 'Chemical properties of Carboxylic Acid',
        'Physical Properties of Carbonyl Compounds and Carboxylic Acid',
        'Amines', 'Introduction,Structure of Amines', 'Classification Of Amines ,Nomenclature',
        'identification of primary, secondary, and tertiary amines and their basic character', 'Preparation of Amines',
        'Chemical Reactions Of Amines & Anilines', 'Diazonium Salts', 'Physical Properties Importance in synthetic organic chemistry',
        'Biomolecules', 'Carbohydrates', 'CARBOHYDRATES - Classification; aldoses and ketoses: monosaccharides (glucose and fructose)',
        'constituent monosaccharides of oligosaccharides (sucrose, lactose, and maltose)', 'Proteins', 'Vitamins', 'Nucleic acids',
        'Polymers', 'Introduction', 'Classification of Polymers', 'Types of Polymerization', 'Molecular masses of polymers',
        'Biodegradable polymers', 'Polymers of commercial importance', 'Chemistry in Everyday Life', 'Drugs and their classification',
        'Drug-target interaction', 'Therapeutic action of different classes of drugs', 'Chemicals in food', 'Cleansing agents'
    ],
    'Physical Chemistry': [
        'Some Basic Concept of Chemistry', 'Dalton\'s Atomic Theory', 'Types of partical and its calculation',
        'Molar Mass, AMU, Mole', 'Mole concept, Average molar Mass', 'VD, Mass % Age, Average Molar Mass',
        'Stoichiometry, Limiting reagent', '% age yield, Impure sample, Laws of chemical combination',
        'EF & EF Concentration Terms', 'Concentration Term Continuous', 'Equivalents Mass, Normality',
        'Concentration of mixture', 'Law of equivalent', 'Significant Feature',
        'Redox Reaction', 'Oxidation,Reduction and Oxidation Number Calculation', 'n-Factor Calculation',
        'Balancing of Redox Reactions', 'Redox Titrations',
        'Solutions', 'Solution', 'vapour pressure', 'Binary Solution and Concentration Terms', 'Solubility and Henry Law',
        'Raoult\'s law & its application', 'Ideal & non ideal solutions', 'Colligative properties',
        'Abnormal molar mass',
        'Thermodynamics', 'Thermodynamics Parameters', 'Pressure – volume work', 'Work done in various processes',
        'First law of thermodynamics', 'Heat Capacity', 'Adiabatic work', 'Spontaneity of processes , Entropy',
        'Gibbs Free Energy', 'Second law of thermodynamics', 'Thermochemistry',
        'Chemical Equilibrium', 'Introduction to Chemical Equilibrium', 'Equilibrium Constant & Characteristics',
        'Applications of Equilibrium Constant', 'Le Chatelier\'s principle',
        'Ionic Equilibrium', 'Introduction', 'Ionic product of water & pH concept', 'Salt Hydrolysis',
        'pH of salt solution', 'Solubility product', 'Buffer solution concept', 'Indicators & titration',
        'Electrochemistry', 'Introduction to Electrolysis & Laws of electrolysis', 'Electrolytic cell',
        'Faraday\'s Law', 'Qualitative and quantitative aspects of Electrolysis', 'Galvanic cell',
        'Electrochemical series', 'Nernst equation', 'Anomalous behaviour',
        'Chemical Kinetics', 'Introduction', 'Rate of reaction', 'Factors affecting rate of reaction',
        'Rate law and rate constant', 'Order and molecularity of reaction', 'Integrated rate equations',
        'Half-life & methods to determine order of reaction', 'Temperature dependence of reaction rates',
        'Arrhenius equation', 'Catalysis', 'Collision theory', 'Surface Chemistry', 'Adsorption',
        'Catalysis', 'Colloids', 'Emulsions', 'Atomic Structure', 'Discovery of subatomic particles',
        'Atomic models', 'Quantum mechanical model', 'Quantum numbers', 'Electronic configuration',
        'Chemical Bonding', 'Ionic bond', 'Covalent bond', 'VSEPR theory', 'Hybridization', 'Molecular orbital theory',
        'Hydrogen bonding', 'States of Matter', 'Gaseous state', 'Liquid state', 'Solid state',
        'Surface Chemistry', 'Adsorption', 'Catalysis', 'Colloids', 'Emulsions'
    ],
    'Botany': [
        'Cell - The Unit of Life', 'What is a Cell ? Discovery of the Cell Microscopy Cell Theory',
        'Overview of Cell Types of Cell Structure Prokaryotic cell Prokaryotic cells', 'Eukaryotic cells',
        'Difference by A Prokaryotic Vs Eukaryotic cell',
        'Cell Cycle and Cell Division', 'Introduction', 'Phases of the Cell Cycle', 'Mitosis',
        'Mitotic Inhibitors', 'Special Type of Mitosis', 'Meiosis', 'Types of Meiosis Nondisjunction',
        'The Living World', 'Introduction What Is Living? Diversity in the Living World',
        'Biological Classification', 'Classification', 'Kingdom : Monera Kingdom : Protista',
        'Kingdom : Fungi', 'KINGDOM Plantae and animals Symbiotic Associations', 'Viruses', 'Prions',
        'Plant Kingdom', 'Types of Classification Systems', 'Algae', 'Bryophytes', 'Pteridophytes',
        'Gymnosperms', 'Angiosperms',
        'Morphology of Flowering Plants', 'Introduction', 'The Root', 'The Stem', 'The Leaf',
        'The Inflorescence', 'The Flower', 'The Fruit', 'The Seed',
        'Semi-Technical Description of a Typical Flowering Plant and Description of Some Important Families',
        'Anatomy of Flowering Plants', 'Introduction', 'Meristematic Tissues', 'Permanent Tissues',
        'The Tissue System', 'Anatomy of Dicotyledonous and Monocotyledonous Plants: Root',
        'Anatomy of Dicotyledonous and Monocotyledonous Plants: Stem',
        'Anatomy of Dicotyledonous and Monocotyledonous Plants: Leaf',
        'Secondary Growth',
        'Respiration in Plants', 'Introduction', 'Glycolysis or EMP pathway', 'Fermentation',
        'Aerobic respiration', 'The Respiratory Balance Sheet and Amphibolic Pathway',
        'Respiratory Quotient',
        'Photosynthesis in Higher Plants', 'Introduction', 'What Do We Know Early Experiments',
        'Site of Photosynthesis and Pigments Involved in Photosynthesis',
        'What Is Light Reaction and Electron Transport Chain', 'ATP and NADPH Use and Calvin Cycle',
        'Hatch and Slack Pathway, Photorespiration',
        'Difference between C3 and C4 pathway, CAM pathway and Factors affecting photosynthesis',
        'Plant Growth and Development', 'Introduction and Seed Germination', 'Growth',
        'Differentiation, Dedifferentiation and Redifferentiation and Development',
        'Plant Growth Regulators', 'Photoperiodism', 'Vernalisation',
        'Sexual Reproduction in Flowering Plant', 'Flower- A Fascinating Organ of Angiosperms',
        'Pre-Fertilization - Structures and Events', 'Pollination', 'Incompatibility',
        'Artificial Hybridization', 'Double Fertilization',
        'Post-Fertilization : Structures and Events', 'Seed', 'Fruit',
        'Molecular Basis of Inheritance', 'Introduction', 'The DNA', 'Central Dogma',
        'Packaging of DNA Helix', 'The Search For Genetic Material', 'RNA world',
        'DNA Replication', 'Genetic Code', 'HNA The Adapter Molecule', 'Translation',
        'Regulation of Gene Expression', 'Human Genome Project', 'DNA Fingerprinting',
        'Principles of Inheritance and Variation', 'Introduction', 'Genetic Terminology',
        'Mendel\'s Laws of Inheritance', 'Examples to Mendelian Principles',
        'Inheritance of Two Gene', 'Polygenic Inheritance and Pleiotropy',
        'Post-Mendelian', 'Sex Determination', 'Mutation',
        'Genetic Disorders: Mendelian Disorders', 'Genetic Disorders: Chromosomal Diseases',
        'Cytoplasmic Inheritance', 'Dosage Compensation',
        'Microbes in Human Welfare', 'Introduction', 'Microbes in Household Products',
        'Microbes in Sewage Treatment', 'Microbes in Production of Biogas',
        'Microbes in Organic Farming', 'Microbes as Biofertilizers', 'Biocontrol Agents',
        'Organisms and Population', 'Introduction', 'Response to Abiotic Factors',
        'Adaptations', 'Populations Growth Models', 'Carrying Capacity',
        'Environmental Resistance', 'Life History Variations', 'Population Interactions',
        'Ecosystem', 'Introduction', 'Pond Ecosystem', 'Structure of Pond Ecosystem',
        'Food Chain', 'Ecological Pyramids', 'Ecological Succession',
        'Biodiversity and Conservation', 'Biodiversity', 'Loss of Biodiversity',
        'Biodiversity Conservation'
    ],
    'Zoology': [
        'Structural Organization in Animals', 'Tissues', 'Animal Tissues', 'Epithelium Tissue',
        'Cell Junctions', 'Connective Tissue', 'Muscular Tissue', 'Nervous Tissue', 'FROG',
        'COCKROACH',
        'Breathing and Exchange of Gases', 'Introduction and Respiratory organs in Animals',
        'Human respiratory system : Nostrils, Nasal chamber, Pharynx, Larynx, Trachea',
        'Human respiratory system : Bronchi, Bronchioles (Conducting part), Lungs and Alveoli (Respiratory part)',
        'Mechanism of Breathing : Normal Inspiration and Expiration',
        'Forceful Inspiration and Expiration, Pulmonary Volumes', 'Pulmonary Capacities',
        'Exchange of gases (factors affecting the rate of diffusion), Diffusion membranes',
        'Partial pressures of Oxygen and Carbon dioxide, exchange of gases between blood and Tissues',
        'Transport of Oxygen', 'Transport of Carbon dioxide and Factors affecting the Haemoglobin oxygen dissociation',
        'Regulation of Respiration (Nervous and Chemical regulation)', 'Disorders of Respiratory system',
        'Body Fluids and Circulation', 'Introduction to body fluids', 'Blood',
        'Blood - Formed Element', 'Blood Groups', 'Coagulation of Blood', 'Lymph',
        'Circulatory Pathways', 'Double Circulation', 'Coronary Circulation',
        'Human Circulatory System', 'Cardiac Cycle', 'Heart Sounds', 'Blood Vessels',
        'Portal system', 'ECG', 'Regulation of Cardiac Activity', 'Disorders of Circulatory System',
        'Excretory Products & their Elimination', 'Introduction', 'Excretory Structures',
        'Human Excretory System', 'LS of kidney', 'Nephron', 'Mechanism of Urine formation',
        'Functions of The Tubule', 'Mechanism of concentration of filtrate', 'Micturition',
        'Urine', 'Role of Other Organs in Excretion', 'Regulation of Kidney Function - Kidney',
        'Regulation of Kidney Function - Hypothalamus', 'Regulation of Kidney Function - Adrenal cortex',
        'Regulation of Kidney Function - Adrenal medulla', 'Regulation of Kidney Function - Heart',
        'Regulation of GFR', 'Counter current mechanism', 'Disorders of the Excretory System',
        'Treatment for renal failure',
        'Locomotion & Movement', 'Introduction', 'Locomotory organs', 'Types of Movement',
        'Muscles', 'Types of Muscle', 'Skeletal muscles', 'Structure of contractile proteins',
        'Mechanism of Muscle Contraction', 'Mechanism of Muscle Relaxation', 'Red & White Muscles',
        'Skeletal system', 'Axial skeleton', 'Appendicular skeleton', 'Joints', 'Lever system',
        'Disorders related to muscular system',
        'Neural Control & Coordination', 'Introduction', 'Neural system', 'Human neural system',
        'Neuron', 'Generation and conduction of nerve impulse', 'Transmission of Impulses',
        'Synapse', 'Mechanism of impulse transmission', 'Neurotransmitters',
        'Central nervous system(CNS)', 'Human Brain', 'Spinal cord',
        'Chemical Coordination & Integration', 'Introduction', 'Endocrine glands', 'Hormones',
        'Types of hormones', 'Hypothalamus', 'Pituitary gland/Hypophysis', 'Thyroid gland',
        'Parathyroid gland', 'Thymus gland', 'Adrenal gland', 'Adrenal cortex', 'Adrenal medulla',
        'Pancreas', 'Gonads', 'Testes', 'Leydig cells', 'Disorders of testes', 'Ovaries',
        'Disorders of ovaries', 'Hormonal action', 'Hormones of Heart, kidney and Gastrointestinal Tract',
        'Hormonal Feedback',
        'Animal Kingdom', 'Introduction', 'Kingdom-Animalia', 'Basis of Classification',
        'Phylum- Porifera', 'Phylum- Coelenterata/Cnidaria', 'Phylum- Ctenophora',
        'Phylum- Platyhelminthes', 'Phylum- Aschelminthes/ Nemathelminthes', 'Phylum-Annelida',
        'Phylum-Arthropoda', 'Phylum- Mollusca', 'Phylum- Echinodermata', 'Phylum- Hemichordata',
        'Phylum-Chordata', 'Subphylum- Urochordata', 'Subphylum- Cephalochordata',
        'Subphylum- Vertebrata', 'Class- Cyclostomata', 'Superclass- Pisces (Class- Chondrichthyes)',
        'Superclass- Pisces (Class- Osteichthyes)', 'Superclass- Tetrapoda (Class – Amphibia)',
        'Superclass- Tetrapoda (Class – Reptiles)', 'Superclass- Tetrapoda (Class – Aves)',
        'Superclass- Tetrapoda (Class – Mammalia)',
        'Biomolecules', 'Introduction', 'Method to analyze chemical composition', 'Metabolites',
        'Micromolecules', 'Carbohydrates', 'Amino acids', 'Proteins', 'Lipids',
        'Simple lipids', 'Compound lipids', 'Derived lipids', 'Nucleic acids', 'RNA', 'DNA',
        'Enzymes',
        'Human Reproduction', 'Human reproductive system', 'Male reproductive system',
        'Female reproductive system', 'Gametogenesis', 'Spermatogenesis', 'Sperm',
        'Structure of sperm', 'Oogenesis', 'Differences between spermatogenesis and oogenesis',
        'Ovum', 'Menstrual cycle', 'Fertilisation to Implantation', 'Sex Determination of Foetus',
        'Pregnancy & embryonic development', 'Parturition & Lactation',
        'Reproductive Health', 'Reproductive health', 'Population', 'Contraceptive methods',
        'Medical termination of pregnancy', 'Sexually transmitted diseases(STDs)', 'Infertility',
        'Assisted reproductive technologies(ARTs)',
        'Human Health and Diseases', 'Introduction', 'Protozoan Disease', 'Immunity',
        'Innate immunity', 'Acquired immunity', 'Lymphoid organs', 'Immunisation',
        'Vaccination', 'Transplantation', 'Allergy', 'Autoimmunity',
        'Immunodeficiency disorders', 'Cancer', 'Drug abuse', 'Alcohol abuse',
        'Tobacco abuse', 'Adolescence', 'Addiction and dependence',
        'Biotechnology: Principles & Processes', 'Introduction', 'Principles of biotechnology',
        'Genetic engineering/Recombinant DNA technology', 'Tools of rDNA technology',
        'Process of rDNA', 'Isolation of DNA', 'Separation and isolation of DNA fragments',
        'Vector', 'Amplification of gene of interest', 'Insertion of rDNA into host cell',
        'Obtaining the foreign gene product',
        'Biotechnology and its Applications', 'Introduction',
        'Biotechnological applications in agriculture', 'Biotechnological applications in medicine',
        'Molecular Diagnostics', 'Transgenic animals', 'Ethical issues',
        'Evolution', 'Origin of life', 'Theory of origin of life', 'Evolution',
        'Evidences of evolution', 'Adaptive radiation', 'Theory of organic evolution',
        'Hardy-weinberg principle', 'Natural selection and artificial selection',
        'Lederberg\'s replica plate experiment', 'Speciation', 'A brief account on evolution',
        'Origin and evolution of man'
    ]
}
